version: "3.9"

services:
  asp:
    image: xpymb/rpgasp
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5068
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    ports:
      - 5068:5068
  
  react:
    build:
      context: ./src/xpymb.testexercises.rpg.react
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
